language: cpp

git:
  submodules: false

compiler:
    - clang

before_install:
    - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
    - git submodule init
    - git submodule sync
    - git submodule update

install:
    - sudo apt-get install libboost-all-dev libbz2-dev libssl-dev python-dev uuid-dev libglew-dev freeglut3-dev
    - Boost/install $(lsb_release -cs)

script:
    - ./animray/compile toolset=$CC -q animray tests examples

