#!/bin/bash
cd `dirname $0`

if test -e metachatr
then {
    git submodule sync
    git submodule update
}
else {
    git submodule sync
    git submodule update
    cd metachatr
    git checkout master
    git flow init -d
    cd ..
}
fi

svn co http://svn.felspar.com/external/Boost \
    Boost
Boost/install 49 0

svn co https://svn.felspar.com/external/crypto++ \
    crypto++
svn co https://svn.felspar.com/external/OpenSSL \
    OpenSSL

svn co http://svn.felspar.com/public/fost-base/stable/fost-base \
    fost-base
svn co http://svn.felspar.com/public/fost-internet/stable/fost-internet \
    fost-internet
svn co http://svn.felspar.com/public/fost-orm/stable/fost-orm \
    fost-orm
svn co http://svn.felspar.com/public/fost-py/stable/fost-py \
    fost-py

animray/compile $*
