#!/bin/bash
cd `dirname $0`

git pull
git submodule init
git submodule sync
git submodule update

Boost/install 53 0

svn co http://svn.felspar.com/public/fost-base/stable/fost-base \
    fost-base
svn co http://svn.felspar.com/public/fost-internet/stable/fost-internet \
    fost-internet
svn co http://svn.felspar.com/public/fost-orm/stable/fost-orm \
    fost-orm
svn co http://svn.felspar.com/public/fost-py/stable/fost-py \
    fost-py

animray/compile $*
