#!/usr/bin/env bash
cd $(dirname $0)
mkdir -p build.tmp/{clang,gcc}-{debug,release}


CMAKE="cmake -G Ninja ."


export CC=gcc
export CXX=g++

$CMAKE -B build.tmp/gcc-debug \
    -DCMAKE_INSTALL_PREFIX=dist/gcc-debug

$CMAKE -B build.tmp/gcc-release \
    -DCMAKE_INSTALL_PREFIX=dist/gcc-release \
    -DCMAKE_BUILD_TYPE=Release


export CC=clang
export CXX=clang++

$CMAKE -B build.tmp/clang-debug \
    -DCMAKE_INSTALL_PREFIX=dist/clang-debug

$CMAKE -B build.tmp/clang-release \
    -DCMAKE_INSTALL_PREFIX=dist/clang-release \
    -DCMAKE_BUILD_TYPE=Release


export CXXFLAGS=-stdlib=libc++

$CMAKE -B build.tmp/clang-debug-libc++ \
    -DCMAKE_INSTALL_PREFIX=dist/clang-debug-libc++

$CMAKE -B build.tmp/clang-release-libc++ \
    -DCMAKE_INSTALL_PREFIX=dist/clang-release-libc++ \
    -DCMAKE_BUILD_TYPE=Release


CUDA_PATH=${CUDA_PATH:-/usr/lib/cuda}

$CMAKE -B build.tmp/clang-debug-cuda \
    -DCUDA_PATH=${CUDA_PATH} \
    -DCMAKE_INSTALL_PREFIX=dist/clang-debug-cuda

$CMAKE -B build.tmp/clang-release-cuda \
    -DCMAKE_INSTALL_PREFIX=dist/clang-release-cuda \
    -DCUDA_PATH=${CUDA_PATH} \
    -DCMAKE_BUILD_TYPE=Release
