#!/usr/bin/env bash
cd $(dirname $0)

mkdir -p build.tmp/{gcc,clang}-{debug,release}

CMAKE="cmake -G Ninja . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"

$CMAKE -B build.tmp/gcc-debug \
    -DCMAKE_INSTALL_PREFIX=dist/gcc-debug

$CMAKE -B build.tmp/gcc-release \
    -DCMAKE_INSTALL_PREFIX=dist/gcc-release \
    -DCMAKE_BUILD_TYPE=Release

CC=clang CXX=clang++ $CMAKE -B build.tmp/clang-debug \
    -DCMAKE_INSTALL_PREFIX=dist/clang-debug

CC=clang CXX=clang++ $CMAKE -B build.tmp/clang-release \
    -DCMAKE_INSTALL_PREFIX=dist/clang-release \
    -DCMAKE_BUILD_TYPE=Release
