#!/usr/bin/env bash

time (
        # User specified targets
        ninja -C ./build.tmp/clang-debug $* &&
        # Debug builds
        ninja -C ./build.tmp/clang-debug all check &&
        ninja -C ./build.tmp/gcc-debug all check &&
        # Release builds
        ninja -C ./build.tmp/clang-release all check &&
        ninja -C ./build.tmp/gcc-release all check &&
        # stdlib=libc++
        ninja -C ./build.tmp/clang-debug-libc++ all check &&
        ninja -C ./build.tmp/clang-release-libc++ all check &&
        # CUDA
        ninja -C ./build.tmp/clang-debug-cuda all check &&
        ninja -C ./build.tmp/clang-release-cuda all check &&
        true
    ) && (
        find ./include/ ./scenes/ ./tests/ -name \*.\?pp -print | xargs clang-format -i
    )
