version: 2.1

executors:
  clang:
    docker:
    - image: fost/circleci
    environment:
      CC: clang
      CXX: clang++
  gcc:
    docker:
    - image: fost/circleci

jobs:
  build:
    parameters:
      compiler:
        type: executor
      variant:
        type: string
    executor: << parameters.compiler >>
    steps:
      - run:
          name: cmake
          command: |
            mkdir build.tmp
            cmake -S . -B build.tmp -G Ninja -DCMAKE_BUILD_TYPE=<< parameters.variant >> $CMAKE_EXTRA
      - run:
          name: ninja
          command: ninja -j1 -C build.tmp
      - run:
          name: check tests
          command: ninja -j1 -C build.tmp check

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              compiler: [gcc, clang]
              variant: [Debug, Release]
