version: 2.1

executors:
  clang:
    docker:
    - image: fost/circleci
    environment:
      CC: clang
      CXX: clang++
      CXXFLAGS: "-stdlib=libc++"
      LD_FLAGS: "-stdlib=libc++"
      BOOST_EXTRA_OPTS: "cxxflags=-stdlib=libc++ linkflags=-stdlib=libc++"
      CMAKE_EXTRA: '-DBOOST_TOOLSET=clang-10 -DBOOST_VMINOR=66'
  gcc:
    docker:
    - image: fost/circleci
    environment:
      CC: gcc-10
      CXX: g++-10
      CMAKE_EXTRA: ''

jobs:
  build:
    parameters:
      compiler:
        type: executor
      variant:
        type: string
    executor: << parameters.compiler >>
    steps:
      - checkout
      - run:
          name: submodules
          command: |
            git submodule update --init --recursive
            ln -s /opt/fost-boost/boost Boost/boost
      - run:
          name: cmake
          command: |
            mkdir build.tmp
            cmake -S . -B build.tmp -G Ninja -DCMAKE_BUILD_TYPE=<< parameters.variant >> $CMAKE_EXTRA
      - run:
          name: ninja
          command: ninja -j1 -C build.tmp
      - run:
          name: check tests
          command: ninja -j1 -C build.tmp check

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              compiler: [gcc, clang]
              variant: [Debug, Release]
