/*
    Copyright 2014, Kirit Saelensminde.
    http://www.kirit.com/AnimRay

    This file is part of AnimRay.

    AnimRay is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    AnimRay is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with AnimRay.  If not, see <http://www.gnu.org/licenses/>.
*/


#ifndef ANIMRAY_CAMERA_HPP
#define ANIMRAY_CAMERA_HPP
#pragma once


#include <animray/point2d.hpp>


namespace animray {


    /// Camera for 2d imaging
    template< typename E, typename R = std::size_t >
    class flat_camera {
    public:
        /// The type used to measure the height of the camera image
        typedef E extents_type;
        /// The type used to measure the physical resolution of the camera
        typedef R resolution_type;

        /// Constructs a camera whose film is a particular size
        flat_camera(extents_type w, extents_type h,
                resolution_type c, resolution_type r)
        : width(w), height(h), columns(c), rows(r) {
        }

        /// Convert from resolution co-ordinates to world co-ordinates
        point2d< extents_type > operator() (
                resolution_type x, resolution_type y) const {
            return point2d< extents_type >(
                width * ((extents_type(x) + half()) / columns - half()),
                -height * ((extents_type(y) + half()) / rows - half()));
        }

    private:
        constexpr static extents_type half() {
            return extents_type(1) / extents_type(2);
        }
        /// The width of the camera
        extents_type width;
        /// The height of the camera
        extents_type height;
        /// The number of columns
        resolution_type columns;
        /// The number of rows of resolution
        resolution_type rows;
    };


    /// Camera with parallel 3d rays
    template< typename R,
            typename C = flat_camera< typename R::value_type > >
    class ortho_camera {
        /// The 2d camera
        C camera;
    public:
        /// The type of ray generated by the camera
        typedef R ray_type;
        /// The type of 2d camera used to generate initial locations
        typedef C camera_type;
        /// The type used to measure the height of the camera image
        typedef typename camera_type::extents_type extents_type;
        /// The type used to measure the physical resolution of the camera
        typedef typename camera_type::resolution_type resolution_type;

        /// Construct the camera for a particular physical size and resolution
        ortho_camera(extents_type w, extents_type h,
                resolution_type c, resolution_type r,
                extents_type f = extents_type(-1),
                extents_type d = extents_type(1))
        : camera(w, h, c, r), focal_plane(f), direction(d) {
        }

        /// Construct a ray in world co-ordinate space
        ray_type operator() (resolution_type x, resolution_type y) const {
            const animray::point2d<extents_type> pc(camera(x, y));
            typedef typename ray_type::end_type end_type;
            return ray_type(end_type(pc.x(), pc.y(), focal_plane),
                end_type(pc.x(), pc.y(), focal_plane + direction));
        }

    private:
        /// The location of the focal plane for the camera
        extents_type focal_plane;
        /// The amount to offset from the plane when creating the ray
        extents_type direction;
    };


    /// Standard computer graphics camera
    template< typename R,
        typename C = flat_camera< typename R::value_type > >
    class pinhole_camera {
        /// The 2d camera
        C camera;
    public:
        /// The underlying local co-ordinate type
        typedef typename R::value_type local_coord_type;
        /// The type of ray generated by the camera
        typedef R ray_type;
        /// The type of 2d camera used to generate initial locations
        typedef C camera_type;
        /// The type used to measure the height of the camera image
        typedef typename camera_type::extents_type extents_type;
        /// The type used to measure the physical resolution of the camera
        typedef typename camera_type::resolution_type resolution_type;

        /// Construct the camera for a particular physical size and resolution
        pinhole_camera(extents_type w, extents_type h,
                resolution_type c, resolution_type r,
                extents_type l, extents_type f= extents_type(0))
        : camera(w, h, c, r), focal_plane(f), focal_length(l) {
        }

        /// The camera is invisible in any scene
        fostlib::nullable< ray_type > intersection(
                const ray_type &by) const {
            return fostlib::null;
        }
        /// The camera is invisible in any scene
        bool occludes(const ray_type &by,
                const local_coord_type epsilon) const {
            return false;
        }

        /// Build a ray that starts from the requested pixel
        ray_type operator() (resolution_type x, resolution_type y) const {
            const animray::point2d<extents_type> pc(camera(x, y));
            typedef typename ray_type::end_type end_type;
            return ray_type(
                end_type(extents_type(0), extents_type(0), focal_plane),
                end_type(pc.x(), pc.y(), focal_plane + focal_length));
        }

    private:
        /// The location of the focal plane for the camera
        extents_type focal_plane;
        /// The focal length
        extents_type focal_length;
    };


}


#endif // ANIMRAY_CAMERA_HPP
