/*
    Copyright 2014, Kirit Saelensminde.
    http://www.kirit.com/AnimRay

    This file is part of AnimRay.

    AnimRay is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    AnimRay is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with AnimRay.  If not, see <http://www.gnu.org/licenses/>.
*/


#ifndef ANIMRAY_CAMERA_HPP
#define ANIMRAY_CAMERA_HPP
#pragma once


#include <animray/point2d.hpp>
#include <random>


namespace animray {


    /// Camera for 2d imaging
    template< typename E, typename R = std::size_t >
    class flat_camera {
    public:
        /// The type used to measure the height of the camera image
        typedef E extents_type;
        /// The type used to measure the physical resolution of the camera
        typedef R resolution_type;

        /// Constructs a camera whose film is a particular size
        flat_camera(extents_type w, extents_type h,
                resolution_type c, resolution_type r)
        : width(w), height(h), columns(c), rows(r) {
        }

        /// Give a value for the width of a pixel in world co-ordinates
        extents_type pixel_width() const {
            return width() / columns();
        }
        /// Give a value for the height of a pixel in world co-ordinates
        extents_type pixel_height() const {
            return height() / rows();
        }

        /// Convert from resolution co-ordinates to world co-ordinates
        point2d< extents_type > operator() (
                resolution_type x, resolution_type y) const {
            return point2d< extents_type >(
                width() * ((extents_type(x) + half()) / columns() - half()),
                -height() * ((extents_type(y) + half()) / rows() - half()));
        }

        /// The width of the camera
        fostlib::accessors<const extents_type> width;
        /// The height of the camera
        fostlib::accessors<const extents_type> height;
        /// The number of columns
        fostlib::accessors<const resolution_type> columns;
        /// The number of rows of resolution
        fostlib::accessors<const resolution_type> rows;

        /// Useful constant
        constexpr static extents_type half() {
            return extents_type(1) / extents_type(2);
        }
    };


    /// Camera that introduces random 2d jitter on the sample locations
    template< typename E, typename C = flat_camera< E > >
    class flat_jitter_camera {
        /// The camera performing the base mapping
        C inner_camera;
        /// The entropy generator
        mutable std::default_random_engine generator;
        /// The distribution for the jitter
        mutable std::uniform_real_distribution<E> jitter;
    public:
        /// The type used to measure the height of the camera image
        typedef E extents_type;
        /// The type used to measure the physical resolution of the camera
        typedef typename C::resolution_type resolution_type;

        /// Constructs a camera whose film is a particular size
        flat_jitter_camera(extents_type w, extents_type h,
                resolution_type c, resolution_type r)
        : inner_camera(w, h, c, r),
                jitter(-inner_camera.half(), +inner_camera.half()) {
        }

        /// Map between pixel co-ordinates and world co-ordinates
        point2d< extents_type > operator() (
                resolution_type x, resolution_type y) const {
            return inner_camera(x, y) +
                point2d< extents_type >(
                    jitter(generator) * inner_camera.pixel_width(),
                    jitter(generator) * inner_camera.pixel_height());
        }
    };


    /// Camera with parallel 3d rays
    template< typename R,
            typename C = flat_camera< typename R::value_type > >
    class ortho_camera {
        /// The 2d camera
        C camera;
    public:
        /// The type of ray generated by the camera
        typedef R ray_type;
        /// The type of 2d camera used to generate initial locations
        typedef C camera_type;
        /// The type used to measure the height of the camera image
        typedef typename camera_type::extents_type extents_type;
        /// The type used to measure the physical resolution of the camera
        typedef typename camera_type::resolution_type resolution_type;

        /// Construct the camera for a particular physical size and resolution
        ortho_camera(extents_type w, extents_type h,
                resolution_type c, resolution_type r,
                extents_type f = extents_type(-1),
                extents_type d = extents_type(1))
        : camera(w, h, c, r), focal_plane(f), direction(d) {
        }

        /// Construct a ray in world co-ordinate space
        ray_type operator() (resolution_type x, resolution_type y) const {
            const animray::point2d<extents_type> pc(camera(x, y));
            typedef typename ray_type::end_type end_type;
            return ray_type(end_type(pc.x(), pc.y(), focal_plane),
                end_type(pc.x(), pc.y(), focal_plane + direction));
        }

    private:
        /// The location of the focal plane for the camera
        extents_type focal_plane;
        /// The amount to offset from the plane when creating the ray
        extents_type direction;
    };


}


#endif // ANIMRAY_CAMERA_HPP
