#!/bin/bash
cd `dirname $0`

export VARIANTS=$*

if test -e /proc/
then {
    export CPUCOUNT=`grep -c ^processor /proc/cpuinfo`
    export TOOLSET=toolset=clang
}
else {
    export CPUCOUNT=`sysctl -n hw.ncpu`
    export TOOLSET=toolset=darwin
    export LANG=C
}
fi

if ../bjam -j$CPUCOUNT $TOOLSET $VARIANTS `../python.opts.sh`
then {
    echo animray $* OK
    exit 0
} else {
    exit 1
}
fi
