#!/bin/bash
cd `dirname $0`

export VARIANTS=$*

if test -e /proc/
then {
    export CPUCOUNT=`grep -c ^processor /proc/cpuinfo`
    export TOOLSET=gcc
}
else {
    export CPUCOUNT=`sysctl -n hw.ncpu`
    export TOOLSET=darwin
    export LANG=C
}
fi

if ../bjam -j$CPUCOUNT toolset=$TOOLSET $VARIANTS `../python.opts.sh`
then {
    echo animray $* OK
    exit 0
} else {
    exit 1
}
fi
