/*
    Copyright 2014, Kirit Saelensminde.
    http://www.kirit.com/AnimRay

    This file is part of AnimRay.

    AnimRay is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    AnimRay is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with AnimRay.  If not, see <http://www.gnu.org/licenses/>.
*/


#ifndef ANIMRAY_CAMERA_ORTHO_HPP
#define ANIMRAY_CAMERA_ORTHO_HPP
#pragma once


#include <animray/camera/flat.hpp>


namespace animray {


    /// Camera with parallel 3d rays
    template< typename R,
            typename C = flat_camera< typename R::local_coord_type > >
    class ortho_camera {
        /// The 2d camera
        C camera;
    public:
        /// The type of ray generated by the camera
        typedef R ray_type;
        /// The type of 2d camera used to generate initial locations
        typedef C camera_type;
        /// The type used to measure the height of the camera image
        typedef typename camera_type::extents_type extents_type;
        /// The type used to measure the physical resolution of the camera
        typedef typename camera_type::resolution_type resolution_type;

        /// Construct the camera for a particular physical size and resolution
        ortho_camera(extents_type w, extents_type h,
                resolution_type c, resolution_type r,
                extents_type f = extents_type(-1),
                extents_type d = extents_type(1))
        : camera(w, h, c, r), focal_plane(f), direction(d) {
        }

        /// Construct a ray in world co-ordinate space
        ray_type operator() (resolution_type x, resolution_type y) const {
            const animray::point2d<extents_type> pc(camera(x, y));
            typedef typename ray_type::end_type end_type;
            return ray_type(end_type(pc.x(), pc.y(), focal_plane),
                end_type(pc.x(), pc.y(), focal_plane + direction));
        }

    private:
        /// The location of the focal plane for the camera
        extents_type focal_plane;
        /// The amount to offset from the plane when creating the ray
        extents_type direction;
    };


}


#endif // ANIMRAY_CAMERA_ORTHO_HPP
